name: SPIRE
favicon: null
layout_spectrum: 0.8382937593851238
typography_spectrum: 0.5283905807882547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfd'
    - '#401818'
    - '#c60210'
    - '#c2c3c7'
    - '#6a6b6f'
  brandStrength: 0.9463237393647432
  lightness: 0.2873910912312567
  saturation: 0.7944694065954536
  rhythmicContrast: 0.26699274661950767
purpose: []
